// Auto-generated by scripts/generate-cubism-export.js
import * as _file_0 from "@cubism/cubismdefaultparameterid";
import * as _file_1 from "@cubism/cubismframeworkconfig";
import * as _file_2 from "@cubism/cubismmodelsettingjson";
import * as _file_3 from "@cubism/effect/cubismbreath";
import * as _file_4 from "@cubism/effect/cubismeyeblink";
import * as _file_5 from "@cubism/effect/cubismpose";
import * as _file_6 from "@cubism/icubismallcator";
import * as _file_7 from "@cubism/icubismmodelsetting";
import * as _file_8 from "@cubism/id/cubismid";
import * as _file_9 from "@cubism/id/cubismidmanager";
import * as _file_10 from "@cubism/live2dcubismframework";
import * as _file_11 from "@cubism/math/cubismmath";
import * as _file_12 from "@cubism/math/cubismmatrix44";
import * as _file_13 from "@cubism/math/cubismmodelmatrix";
import * as _file_14 from "@cubism/math/cubismtargetpoint";
import * as _file_15 from "@cubism/math/cubismvector2";
import * as _file_16 from "@cubism/math/cubismviewmatrix";
import * as _file_17 from "@cubism/model/cubismmoc";
import * as _file_18 from "@cubism/model/cubismmodel";
import * as _file_19 from "@cubism/model/cubismmodeluserdata";
import * as _file_20 from "@cubism/model/cubismmodeluserdatajson";
import * as _file_21 from "@cubism/model/cubismusermodel";
import * as _file_22 from "@cubism/motion/acubismmotion";
import * as _file_23 from "@cubism/motion/cubismexpressionmotion";
import * as _file_24 from "@cubism/motion/cubismexpressionmotionmanager";
import * as _file_25 from "@cubism/motion/cubismmotion";
import * as _file_26 from "@cubism/motion/cubismmotioninternal";
import * as _file_27 from "@cubism/motion/cubismmotionjson";
import * as _file_28 from "@cubism/motion/cubismmotionmanager";
import * as _file_29 from "@cubism/motion/cubismmotionqueueentry";
import * as _file_30 from "@cubism/motion/cubismmotionqueuemanager";
import * as _file_31 from "@cubism/physics/cubismphysics";
import * as _file_32 from "@cubism/physics/cubismphysicsinternal";
import * as _file_33 from "@cubism/physics/cubismphysicsjson";
import * as _file_34 from "@cubism/rendering/cubismclippingmanager";
import * as _file_35 from "@cubism/rendering/cubismrenderer";
import * as _file_36 from "@cubism/rendering/cubismrenderer_webgl";
import * as _file_37 from "@cubism/rendering/cubismshader_webgl";
import * as _file_38 from "@cubism/type/csmmap";
import * as _file_39 from "@cubism/type/csmrectf";
import * as _file_40 from "@cubism/type/csmstring";
import * as _file_41 from "@cubism/type/csmvector";
import * as _file_42 from "@cubism/utils/cubismdebug";
import * as _file_43 from "@cubism/utils/cubismjson";
import * as _file_44 from "@cubism/utils/cubismjsonextension";
import * as _file_45 from "@cubism/utils/cubismstring";

// Explicitly export Live2DCubismFramework from the main file only
export { Live2DCubismFramework } from "@cubism/live2dcubismframework";

export import CubismDefaultParameterId = _file_0.CubismDefaultParameterId;
export import CSM_LOG_LEVEL_VERBOSE = _file_1.CSM_LOG_LEVEL_VERBOSE;
export import CSM_LOG_LEVEL_DEBUG = _file_1.CSM_LOG_LEVEL_DEBUG;
export import CSM_LOG_LEVEL_INFO = _file_1.CSM_LOG_LEVEL_INFO;
export import CSM_LOG_LEVEL_WARNING = _file_1.CSM_LOG_LEVEL_WARNING;
export import CSM_LOG_LEVEL_ERROR = _file_1.CSM_LOG_LEVEL_ERROR;
export import CSM_LOG_LEVEL_OFF = _file_1.CSM_LOG_LEVEL_OFF;
export import CSM_LOG_LEVEL = _file_1.CSM_LOG_LEVEL;
export import CubismModelSettingJson = _file_2.CubismModelSettingJson;
export import FrequestNode = _file_2.FrequestNode;
export import ICubismAllocator = _file_6.ICubismAllocator;
export import ICubismModelSetting = _file_7.ICubismModelSetting;
export import CubismFramework = _file_10.CubismFramework;
export import Option = _file_10.Option;
export import LogLevel = _file_10.LogLevel;
export import Constant = _file_10.Constant;
export import strtod = _file_10.strtod;
export import csmDelete = _file_10.csmDelete;

export namespace effect {
    export import CubismBreath = _file_3.CubismBreath;
    export import BreathParameterData = _file_3.BreathParameterData;
    export import CubismEyeBlink = _file_4.CubismEyeBlink;
    export import EyeState = _file_4.EyeState;
    export import CubismPose = _file_5.CubismPose;
    export import PartData = _file_5.PartData;
}

export namespace id {
    export import CubismId = _file_8.CubismId;
    export import CubismIdManager = _file_9.CubismIdManager;
}

export namespace math {
    export import CubismMath = _file_11.CubismMath;
    export import CubismMatrix44 = _file_12.CubismMatrix44;
    export import CubismModelMatrix = _file_13.CubismModelMatrix;
    export import CubismTargetPoint = _file_14.CubismTargetPoint;
    export import CubismVector2 = _file_15.CubismVector2;
    export import CubismViewMatrix = _file_16.CubismViewMatrix;
}

export namespace model {
    export import CubismMoc = _file_17.CubismMoc;
    export import ParameterRepeatData = _file_18.ParameterRepeatData;
    export import DrawableColorData = _file_18.DrawableColorData;
    export import PartColorData = _file_18.PartColorData;
    export import DrawableCullingData = _file_18.DrawableCullingData;
    export import CubismModel = _file_18.CubismModel;
    export import CubismModelUserDataNode = _file_19.CubismModelUserDataNode;
    export import CubismModelUserData = _file_19.CubismModelUserData;
    export import CubismModelUserDataJson = _file_20.CubismModelUserDataJson;
    export import CubismUserModel = _file_21.CubismUserModel;
}

export namespace motion {
    export import ACubismMotion = _file_22.ACubismMotion;
    export import BeganMotionCallback = _file_22.BeganMotionCallback;
    export import FinishedMotionCallback = _file_22.FinishedMotionCallback;
    export import CubismExpressionMotion = _file_23.CubismExpressionMotion;
    export import ExpressionParameter = _file_23.ExpressionParameter;
    export import ExpressionBlendType = _file_23.ExpressionBlendType;
    export import ExpressionParameterValue = _file_24.ExpressionParameterValue;
    export import CubismExpressionMotionManager = _file_24.CubismExpressionMotionManager;
    export import CubismMotion = _file_25.CubismMotion;
    export import MotionBehavior = _file_25.MotionBehavior;
    export import CubismMotionPoint = _file_26.CubismMotionPoint;
    export import CubismMotionSegment = _file_26.CubismMotionSegment;
    export import CubismMotionCurve = _file_26.CubismMotionCurve;
    export import CubismMotionEvent = _file_26.CubismMotionEvent;
    export import CubismMotionData = _file_26.CubismMotionData;
    export import CubismMotionCurveTarget = _file_26.CubismMotionCurveTarget;
    export import CubismMotionSegmentType = _file_26.CubismMotionSegmentType;
    export import csmMotionSegmentEvaluationFunction = _file_26.csmMotionSegmentEvaluationFunction;
    export import CubismMotionJson = _file_27.CubismMotionJson;
    export import EvaluationOptionFlag = _file_27.EvaluationOptionFlag;
    export import CubismMotionManager = _file_28.CubismMotionManager;
    export import CubismMotionQueueEntry = _file_29.CubismMotionQueueEntry;
    export import CubismMotionQueueManager = _file_30.CubismMotionQueueManager;
    export import CubismMotionEventFunction = _file_30.CubismMotionEventFunction;
    export import InvalidMotionQueueEntryHandleValue = _file_30.InvalidMotionQueueEntryHandleValue;
}

export namespace physics {
    export import CubismPhysics = _file_31.CubismPhysics;
    export import Options = _file_31.Options;
    export import PhysicsOutput = _file_31.PhysicsOutput;
    export import PhysicsJsonEffectiveForces = _file_32.PhysicsJsonEffectiveForces;
    export import CubismPhysicsParameter = _file_32.CubismPhysicsParameter;
    export import CubismPhysicsNormalization = _file_32.CubismPhysicsNormalization;
    export import CubismPhysicsParticle = _file_32.CubismPhysicsParticle;
    export import CubismPhysicsSubRig = _file_32.CubismPhysicsSubRig;
    export import CubismPhysicsInput = _file_32.CubismPhysicsInput;
    export import CubismPhysicsOutput = _file_32.CubismPhysicsOutput;
    export import CubismPhysicsRig = _file_32.CubismPhysicsRig;
    export import CubismPhysicsTargetType = _file_32.CubismPhysicsTargetType;
    export import CubismPhysicsSource = _file_32.CubismPhysicsSource;
    export import normalizedPhysicsParameterValueGetter = _file_32.normalizedPhysicsParameterValueGetter;
    export import physicsValueGetter = _file_32.physicsValueGetter;
    export import physicsScaleGetter = _file_32.physicsScaleGetter;
    export import CubismPhysicsJson = _file_33.CubismPhysicsJson;
}

export namespace rendering {
    export import CubismClippingManager = _file_34.CubismClippingManager;
    export import ICubismClippingManager = _file_34.ICubismClippingManager;
    export import ClippingContextConstructor = _file_34.ClippingContextConstructor;
    export import CubismRenderer = _file_35.CubismRenderer;
    export import CubismTextureColor = _file_35.CubismTextureColor;
    export import CubismClippingContext = _file_35.CubismClippingContext;
    export import CubismBlendMode = _file_35.CubismBlendMode;
    export import CubismClippingManager_WebGL = _file_36.CubismClippingManager_WebGL;
    export import CubismRenderTextureResource = _file_36.CubismRenderTextureResource;
    export import CubismClippingContext_WebGL = _file_36.CubismClippingContext_WebGL;
    export import CubismRendererProfile_WebGL = _file_36.CubismRendererProfile_WebGL;
    export import CubismRenderer_WebGL = _file_36.CubismRenderer_WebGL;
    export import CubismShader_WebGL = _file_37.CubismShader_WebGL;
    export import CubismShaderManager_WebGL = _file_37.CubismShaderManager_WebGL;
    export import CubismShaderSet = _file_37.CubismShaderSet;
    export import ShaderNames = _file_37.ShaderNames;
    export import vertexShaderSrcSetupMask = _file_37.vertexShaderSrcSetupMask;
    export import fragmentShaderSrcsetupMask = _file_37.fragmentShaderSrcsetupMask;
    export import vertexShaderSrc = _file_37.vertexShaderSrc;
    export import vertexShaderSrcMasked = _file_37.vertexShaderSrcMasked;
    export import fragmentShaderSrcPremultipliedAlpha = _file_37.fragmentShaderSrcPremultipliedAlpha;
    export import fragmentShaderSrcMaskPremultipliedAlpha = _file_37.fragmentShaderSrcMaskPremultipliedAlpha;
    export import fragmentShaderSrcMaskInvertedPremultipliedAlpha = _file_37.fragmentShaderSrcMaskInvertedPremultipliedAlpha;
}

export namespace type {
    export import csmPair = _file_38.csmPair;
    export import csmMap = _file_38.csmMap;
    export import csmRect = _file_39.csmRect;
    export import csmString = _file_40.csmString;
    export import csmVector = _file_41.csmVector;
}

export namespace utils {
    export import CubismDebug = _file_42.CubismDebug;
    export import CubismLogPrint = _file_42.CubismLogPrint;
    export import CubismLogPrintIn = _file_42.CubismLogPrintIn;
    export import CSM_ASSERT = _file_42.CSM_ASSERT;
    export import Value = _file_43.Value;
    export import CubismJson = _file_43.CubismJson;
    export import JsonFloat = _file_43.JsonFloat;
    export import JsonBoolean = _file_43.JsonBoolean;
    export import JsonString = _file_43.JsonString;
    export import JsonError = _file_43.JsonError;
    export import JsonNullvalue = _file_43.JsonNullvalue;
    export import JsonArray = _file_43.JsonArray;
    export import JsonMap = _file_43.JsonMap;
    export import CubismJsonExtension = _file_44.CubismJsonExtension;
    export import CubismString = _file_45.CubismString;
}

